# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Run tests
      run: ./gradlew test -i

    - name: Build jar
      run: ./gradlew bootJar

    - name: Archive jar
      uses: actions/upload-artifact@v2
      with:
        name: balance-analyzer.jar
        path: |
          build/libs/*.jar
