# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-distribution: 'temurin'
          java-version: '21'

      - name: Run tests
        run: ./gradlew test -i

      - name: Build jar
        run: ./gradlew bootJar

      - name: Archive jar
        uses: actions/upload-artifact@v4
        with:
          name: balance-analyzer.jar
          path: |
            build/libs/*.jar
